name: 'Clarify and Improve Issues with OpenAI GPT'
description: 'Uses the OpenAI GPT API to clarify new issues and provide suggestions for improvement.'
inputs:
  api-key:
    description: 'OpenAI API key'
    required: true
  config-file:
    description: 'configuration file name with path.'
    required: false
  model:
    description: 'OpenAI model'
    default: 'text-davinci-003'
  max_tokens:
    description: 'OpenAI max_tokens / section (response length)'
    default: 150
    type: number
    required: false
  add-related-issues-section:
    description: 'Find related issues'
    default: true
    type: boolean
    required: false
  add-summary-section:
    description: 'Add summary'
    default: true
    type: boolean
    required: false
  github-token:
    description: 'GitHub token with the `repo` scope'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: './dist/index.js'
