name: 'Clarify and Improve Issues with OpenAI GPT'
description: 'Uses the OpenAI GPT API to clarify new issues and provide suggestions for improvement.'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  openai-key:
    description: 'OpenAI API key'
    required: true
  debug-mode:
    description: 'Show the prompt in the comment.'
    default: false
    type: boolean
    required: false
  config-file:
    description: 'configuration file name with path.'
    required: false
    default: 'issue-improver-config.json'
  model:
    description: 'OpenAI model'
    default: 'text-davinci-003'
    required: false
  max-tokens:
    description: 'OpenAI max_tokens / section (response length)'
    default: 150
    type: number
    required: false
  add-related-issues-section:
    description: 'Find related issues'
    default: false
    type: boolean
    required: false
  add-label-section:
    description: 'Label suggestion section'
    default: false
    type: boolean
    required: false
  add-summary-section:
    description: 'Add summary'
    default: false
    type: boolean
    required: false
  add-custom-section:
    description: 'Add custom sections'
    default: false
    type: boolean
    required: false
  add-comment-summary-section:
    description: 'Add comment summary'
    default: false
    type: boolean
    required: false
  github-token:
    description: 'GitHub token with the `repo` scope'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: './dist/index.js'
