name: Improve issues

on:
  issues:
    types: [opened, edited]

jobs:
  gpt-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create useful comment with AI
        uses: MaurerKrisztian/issue-improver-action@latest
        with:
          openai-key: ${{ secrets.GPT_KEY }}
          max-tokens: 400
          add-related-issues-section: true
          add-summary-section: true
          add-label-section: true
          add-custom-section: true

#          Other defaults:
#          model: 'text-davinci-003'
#          max-tokens: 200
#          debug-mode: false
#          add-comment-summary-section: false
