name: Improve issues

on:
  issues:
    types: [opened, edited]

jobs:
  gpt-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create useful comment with AI
        uses: MaurerKrisztian/issue-improver-action@latest
        with:
          api-key: ${{ secrets.GPT_KEY }}
          add-summary-section: true
          add-related-issues-section: true
          add-label-section: true
