name: Package and Push to latest branch
on:
  push:
    branches:
      - main # Trigger the workflow only when changes are pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Install dependencies
        run: npm ci # replace with your build script command
      - name: build
        run: npm run package
      - name: Configure git
        run: |
          git config --global user.name "Github bot"
          git config --global user.email "email@mail.com"
          rm .gitignore
          git checkout -b latest
          git add -A
          git commit -a -m "build"
          git push -u origin latest
          git push -u origin latest --force
